Domain\Entities\Layout:
    type: entity
    table: layouts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: name
        picture:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        itemsNumber:
            type: integer
            nullable: false
            options:
                fixed: false
            column: items_number
        type:
            type: integer
            nullable: false
            options:
                default: 0
            column: type

    lifecycleCallbacks: {}
