Domain\Entities\UserDraft:
    type: entity
    table: users_drafts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: json_array
            nullable: false
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        type:
            type: smallint
            nullable: false
            options:
                default: 0
    manyToOne:
        createdBy:
            targetEntity: Domain\Entities\User
            joinColumn:
                name: created_by
                referencedColumnName: id

    lifecycleCallbacks:
            prePersist: [setCreatedAtValue]
            preUpdate: [setUpdatedAtValue]
