Domain\Entities\Group:
    type: entity
    table: groups
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        isActive:
            type: integer
            nullable: false
            options:
                default: 0
            column: is_active
        permissions:
          type: json_array
          nullable: true
          options:
            fixed: false
        stages:
          type: json_array
          nullable: true
          options:
            fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        createdBy:
            targetEntity: Domain\Entities\User
            inversedBy: groups
            joinColumn:
                name: created_by
                referencedColumnName: id

    lifecycleCallbacks:
          prePersist: [setCreatedAtValue]
          preUpdate: [setUpdatedAtValue]
