Domain\Entities\Section:
    type: entity
    table: sections
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: slug
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isBusinessWeek:
            type: smallint
            nullable: false
            options:
                default: 0

    lifecycleCallbacks:
            prePersist: [setCreatedAtValue, setSlug]
            preUpdate: [setUpdatedAtValue, setSlug]
