Domain\Entities\ArticleVersion:
    type: entity
    table: article_versions
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        version:
            type: object
            nullable: false
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToOne:
        createdBy:
            targetEntity: Domain\Entities\User
            joinColumn:
                name: created_by
                referencedColumnName: id
        article:
            targetEntity: Domain\Entities\Article
            inversedBy: versions
            joinColumn:
                name: article_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
