Domain\Entities\Jargon:
    type: entity
    table: jargon
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        enTitle:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        url:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: slug
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        createdBy:
            targetEntity: Domain\Entities\User
            joinColumn:
                name: created_by
                referencedColumnName: id

    manyToMany:
        articles:
            targetEntity: Domain\Entities\Article
            mappedBy: jargon
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setSlug]
        preUpdate: [setUpdatedAtValue, setSlug]
