Domain\Entities\Author:
    type: entity
    table: authors
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: slug
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        createdBy:
            targetEntity: Domain\Entities\User
            inversedBy: authors
            joinColumn:
                name: created_by
                referencedColumnName: id
    lifecycleCallbacks:
            prePersist: [setCreatedAtValue, setSlug]
            preUpdate: [setUpdatedAtValue, setSlug]
