Domain\Entities\Writer:
    type: entity
    table: writers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        imageName:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: image_name
        bio:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        twitterAccountUrl:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: twitter_account_url
        slug:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: slug
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    oneToMany:
        articles:
            targetEntity: Domain\Entities\Article
            mappedBy: writer
    lifecycleCallbacks:
            prePersist: [setCreatedAtValue, setSlug]
            preUpdate: [setUpdatedAtValue, setSlug]
