Domain\Entities\Stock\StockIndustrySubGroup:
    type: entity
    table: stock_industry_subgroups
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        position:
            type: integer
            nullable: false
            options:
                default: 0
        securitiesSortIds:
            type: json_array
            nullable: true
            length: 256
            options:
            column: securities_sort_ids
        slug:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: slug
    manyToOne:
        industryGroup:
          targetEntity: Domain\Entities\Stock\StockIndustryGroup
          nullable: false
          inversedBy: industrySubgroups
          joinColumn:
            name: industry_group_id
            referencedColumnName: id
    manyToMany:
        securities:
            targetEntity: Domain\Entities\Stock\StockSecurity
            inversedBy: industrySubgroups
            joinTable:
                name: stock_industry_sub_group_securities
                joinColumns:
                    industry_sub_group_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    security_id:
                        referencedColumnName: id

    lifecycleCallbacks:
            prePersist: [setSlug]
            preUpdate: [setSlug]
