Domain\Entities\Stock\StockTicker:
    type: entity
    table: stock_tickers
    indexes:
      idIdx:
        columns: [ id ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
        username:
          type: string
          nullable: false
          length: 128
          options:
            fixed: false
          column: user_name
        password:
          type: string
          nullable: false
          length: 512
          options:
            fixed: false
        codes:
          type: array
          nullable: false

    lifecycleCallbacks:
