Domain\Entities\Stock\StockSecuritySuggestion:
    type: entity
    table: stock_securities_suggestions
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
          type: smallint
          nullable: false
          options:
            default: 0
        source:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        message:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
        userIp:
          type: string
          nullable: false
          length: 64
        createdAt:
          type: datetime
          nullable: true
          column: created_at
    manyToOne:
        security:
          targetEntity: Domain\Entities\Stock\StockSecurity
          joinColumn:
            name: security_id
            referencedColumnName: id
            onDelete: "SET NULL"
    lifecycleCallbacks:
      prePersist: [setCreatedAtValue]
